name: 'test'
on:
  push:
    branches: 
      - main
    #schedule:
      #- cron: '1 * * * *'

jobs:
  jd_comment_crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests 
      - name: 'Run script'
        run: python jd_comments.py > a.log
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PWD}}
          subject: 'jd comments'
          body: file//a.log
          attachments: a.log
          to: ${{ secrets.TO }}
          from: GitHub Actions
          content_type: text/html
