name: 'test'
on:
  push:
    branches: 
      - main
    #schedule:
      #- cron: '1 * * * *'

jobs:
  jd_comment_crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests 
      - name: 'Run script'
        run: python jd_comments.py > date +%s.log
